#!/usr/bin/env python3
"""
Phase-robustness study: does the strategy survive moving the day boundary?

The daily bars every backtest here runs on are cut at UTC 00:00 only because
that is the bar the exchange serves. This script re-cuts the same price series
at other hours (see ``orange_quant.data.hourly``), retrains the model on each
re-cut dataset, and compares the results.

Retraining per phase is the point: evaluating a phase-0-trained model on phase-h
features would measure feature drift, not whether the *strategy* holds. Each
phase gets its own train/valid/test on its own bars, so the only thing that
varies is where the day starts.

Reading the output:
  * Tight spread across phases -> the edge is real, and phase 00's numbers are
    trustworthy rather than a lucky cut.
  * Wide spread -> a meaningful share of the backtest is sampling luck. Fix the
    strategy; averaging phases together would only hide it.

Sequential by construction: concurrent runs share the mlruns/ store and corrupt
each other, so phases are never trained in parallel.

Usage:
    python -m scripts.phase_study --phases 0,6,12,18
    python -m scripts.phase_study --phases 0,3,6,9,12,15,18,21 --skip-build
"""

import argparse
import traceback
from pathlib import Path

import pandas as pd
import yaml

GENERATED_DIR = Path("config/generated")
RESULTS_DIR = Path("data/phase_study")

# (label, candidate metric keys) — qlib's exact names vary by version, so match
# the first key that exists, falling back to a substring search.
_METRICS = [
    ("ic",            ["IC"]),
    ("rank_ic",       ["Rank IC"]),
    ("icir",          ["ICIR"]),
    ("rank_icir",     ["Rank ICIR"]),
    ("ann_return",    ["1day.excess_return_with_cost.annualized_return"]),
    ("info_ratio",    ["1day.excess_return_with_cost.information_ratio"]),
    ("max_drawdown",  ["1day.excess_return_with_cost.max_drawdown"]),
]


def _pick_metric(metrics: dict, candidates) -> float:
    for key in candidates:
        if key in metrics:
            return float(metrics[key])
    # Fall back to a unique substring match (qlib renames keys between versions)
    for key in candidates:
        hits = [k for k in metrics if key in k]
        if len(hits) == 1:
            return float(metrics[hits[0]])
    return float("nan")


def make_phase_config(base_config: str, phase: int, venue: str,
                      window: dict = None) -> Path:
    """Write a config identical to the base one but pointed at the phase store.

    Only ``qlib_init.provider_uri`` changes, so the phases share model params,
    strategy params, costs and date splits — the comparison stays clean. The
    generated file is written to disk (not held in memory) so any single phase
    can be re-run on its own, e.g.::

        python -m biance_lgb_momtopk.train generated/binance-lgb-momtopk-h06

    ``window`` additionally overrides the train/valid/test splits, for
    walk-forward evaluation across several out-of-sample periods. It must carry
    a ``name`` plus ``train``/``valid``/``test`` dicts; the resulting file gets a
    ``-w{name}`` suffix so windows never overwrite each other's configs.
    """
    with open(f"config/{base_config}.yaml") as f:
        config = yaml.safe_load(f)

    config.setdefault("qlib_init", {})["provider_uri"] = (
        f"data/qlib_data/{venue}_h{phase:02d}"
    )

    suffix, extra = "", ""
    if window:
        for seg in ("train", "valid", "test"):
            config[seg] = dict(window[seg])
        suffix = f"-w{window['name']}"
        extra = (f"# Walk-forward window {window['name']}: "
                 f"train {window['train']['start']}..{window['train']['end']}, "
                 f"test {window['test']['start']}..{window['test']['end']}\n")

    GENERATED_DIR.mkdir(parents=True, exist_ok=True)
    out = GENERATED_DIR / f"{base_config}-h{phase:02d}{suffix}.yaml"
    header = (f"# GENERATED by scripts/phase_study.py — do not edit.\n"
              f"# {base_config}.yaml re-pointed at the phase-{phase:02d} dataset\n"
              f"# (daily bars cut at {phase:02d}:00 UTC instead of 00:00).\n" + extra)
    out.write_text(header + yaml.safe_dump(config, sort_keys=False))
    return out


def run_phase(base_config: str, phase: int, venue: str) -> dict:
    """Train + backtest one phase, returning its metrics."""
    from orange_quant.experiment import run_from_yaml

    config_path = make_phase_config(base_config, phase, venue)
    print("\n" + "=" * 60)
    print(f"▶ phase {phase:02d} — {config_path}")
    print("=" * 60)

    results = run_from_yaml(str(config_path))
    metrics = results["recorder"].list_metrics()

    row = {"phase": phase}
    row.update({name: _pick_metric(metrics, keys) for name, keys in _METRICS})
    return row


def summarize(df: pd.DataFrame) -> pd.DataFrame:
    """Per-metric dispersion across phases — the actual output of the study."""
    cols = [c for c, _ in _METRICS if c in df]
    stats = df[cols].agg(["mean", "std", "min", "max"]).T
    stats["spread"] = stats["max"] - stats["min"]
    if "phase" in df and 0 in set(df["phase"]):
        stats["phase00"] = df.set_index("phase").loc[0, cols]
    return stats


def main():
    parser = argparse.ArgumentParser(description="Phase-robustness study")
    parser.add_argument("--venue", default="binance", choices=["binance", "hyperliquid"])
    parser.add_argument("--config", default=None,
                        help="Base config name (default: <venue>-lgb-momtopk)")
    parser.add_argument("--phases", default="0,6,12,18",
                        help="Comma-separated hours 0..23")
    parser.add_argument("--skip-build", action="store_true",
                        help="Reuse existing phase datasets instead of rebuilding")
    args = parser.parse_args()

    base_config = args.config or (
        "binance-lgb-momtopk" if args.venue == "binance" else "hyperliquid-lgb-momtopk"
    )
    phases = [int(p) for p in args.phases.split(",") if p.strip()]
    for p in phases:
        if not 0 <= p <= 23:
            raise SystemExit(f"phase out of range: {p}")

    print("=" * 60)
    print(f"🔬 Phase study — {base_config}, phases {phases}")
    print("=" * 60)

    if not args.skip_build:
        from orange_quant.data import hourly
        source = hourly.get_source(args.venue)
        hourly.build_phases(source, phases)

    rows, failed = [], []
    for phase in phases:
        try:
            rows.append(run_phase(base_config, phase, args.venue))
        except Exception as e:  # noqa: BLE001 — one bad phase must not lose the rest
            print(f"❌ phase {phase:02d} failed: {e}")
            traceback.print_exc()
            failed.append(phase)

    if not rows:
        raise SystemExit("Every phase failed; nothing to report")

    df = pd.DataFrame(rows).sort_values("phase").reset_index(drop=True)
    RESULTS_DIR.mkdir(parents=True, exist_ok=True)
    out = RESULTS_DIR / f"{base_config}-phases.csv"

    # Merge rather than overwrite: a rerun of a subset (--phases 0, or a retry
    # of one failure) would otherwise silently discard every other phase's
    # result, and this file is what strategy_sweep's calibration check anchors
    # against. Freshly computed rows win on collision.
    if out.exists():
        prior = pd.read_csv(out)
        df = (pd.concat([prior[~prior["phase"].isin(df["phase"])], df])
              .sort_values("phase").reset_index(drop=True))
    df.to_csv(out, index=False)

    print("\n" + "=" * 60)
    print(f"📊 Per-phase results ({base_config})")
    print("=" * 60)
    print(df.to_string(index=False, float_format=lambda v: f"{v: .4f}"))
    print("\nDispersion across phases:")
    print(summarize(df).to_string(float_format=lambda v: f"{v: .4f}"))
    if failed:
        print(f"\n⚠ phases that failed and are missing above: {failed}")
    print(f"\n💾 {out}")


if __name__ == "__main__":
    main()
